"use client";

/**
 * ReportViewer — renders a ReportPayload as an A4-styled HTML document.
 *
 * Visual reference: the NHS S2 "Rapport de pilotage" PDF Wati uses. The
 * palette, typography (Spectral + Inter), funnel bar, KPI cards with
 * colored top borders, exec messages grid, priority tier banners, vigilance
 * flags and annex tables all mirror that doc so the printed PDF feels
 * like a polished board-ready report — not a generic dashboard dump.
 *
 * The "Télécharger PDF" button triggers window.print() with @page:A4 in
 * the embedded stylesheet — no Puppeteer service needed.
 */

import { useEffect, useMemo, useRef } from "react";
import type { ReportPayload } from "@/lib/reports/types";
import { REPORT_CSS } from "./report-css";

const UI = {
  fr: {
    kicker: "Obesity Care Clinic · Pilotage opérationnel",
    s01: "Synthèse exécutive", s01tag: "Lecture en 30 secondes",
    s02: "Indicateurs de performance", s02tag: "période en cours",
    s03: "Plan d'action — dossiers à traiter", s03tag: "Le cœur du pilotage",
    s04: "Points de vigilance", s04tag: "Regard critique",
    s05: "Annexes — détail complet", s05tag: "Pièce justificative",
    colPatient: "Patient", colPhone: "Téléphone", colReason: "Motif", colWhen: "Quand", colUrgency: "Urgence",
    urgHaute: "Haute", urgMoy: "Moyenne", urgSurv: "Surveillance", urgOk: "OK",
    dossier: "dossier", dossiers: "dossiers",
    downloadPdf: "⤓ Télécharger PDF",
    footerNote: "Note méthodologique.",
    footerSuffix: "Rapport généré automatiquement par Axon · Confidentiel — Obesity Care Clinic.",
    levier: "Levier →",
  },
  en: {
    kicker: "Obesity Care Clinic · Operational Management",
    s01: "Executive Summary", s01tag: "30-second read",
    s02: "Performance Indicators", s02tag: "current period",
    s03: "Action Plan", s03tag: "Core operations",
    s04: "Watchpoints", s04tag: "Critical review",
    s05: "Annexes — full detail", s05tag: "Supporting data",
    colPatient: "Patient", colPhone: "Phone", colReason: "Reason", colWhen: "When", colUrgency: "Urgency",
    urgHaute: "High", urgMoy: "Medium", urgSurv: "Monitor", urgOk: "OK",
    dossier: "case", dossiers: "cases",
    downloadPdf: "⤓ Download PDF",
    footerNote: "Methodology note.",
    footerSuffix: "Report automatically generated by Axon · Confidential — Obesity Care Clinic.",
    levier: "Lever →",
  },
};

const TONE_COLOR_BIG: Record<string, string> = {
  good: "var(--rp-green)",
  warn: "var(--rp-amber)",
  info: "var(--rp-blue)",
  bad: "var(--rp-red)",
};

const FUNNEL_BG = ["var(--rp-ink)", "var(--rp-blue)", "#2E8B57", "var(--rp-green)"];

const PRIO_HEAD_BG: Record<number, string> = {
  1: "var(--rp-red)",
  2: "var(--rp-amber)",
  3: "var(--rp-blue)",
  4: "#5A6B82",
};

const URGENCY_TONE: Record<string, string> = {
  haute: "haute",
  moy: "moy",
  surv: "surv",
  green: "green",
};

const ANNEX_LETTER_BG: Record<string, string> = {
  good: "var(--rp-green)",
  info: "var(--rp-blue)",
  warn: "var(--rp-amber)",
  bad: "var(--rp-red)",
  neutral: "#5A6B82",
};

export function ReportViewer({ report }: { report: ReportPayload }) {
  const containerRef = useRef<HTMLDivElement | null>(null);
  const u = UI[report.lang ?? "fr"];

  // Inject the per-page CSS scoped to .rp-sheet so it doesn't bleed into
  // the rest of the Axon UI. We append it to <head> once and clean up on
  // unmount — repeated mounts share the same <style> via the data-key.
  useEffect(() => {
    const KEY = "axon-report-css";
    if (typeof document === "undefined") return;
    if (document.querySelector(`style[data-key="${KEY}"]`)) return;
    const tag = document.createElement("style");
    tag.dataset.key = KEY;
    tag.textContent = REPORT_CSS;
    document.head.appendChild(tag);
    return () => {
      // Keep the style — repeated viewer mounts re-use it. Only remove on
      // a hot-reload boundary where the document gets a fresh head.
    };
  }, []);

  const funnelFlex = useMemo(() => {
    // Each funnel stage's flex-grow is proportional to its count, so the
    // first stage (largest) gets the widest band, the last gets the thinnest.
    const total = report.funnel.reduce((s, f) => s + f.count, 0) || 1;
    return report.funnel.map((f) => Math.max(6, Math.round((100 * f.count) / total)));
  }, [report.funnel]);

  return (
    <div>
      <div className="rp-toolbar">
        <div>
          <div className="rp-toolbar-title">{report.title}</div>
          <div className="rp-toolbar-sub">{report.subtitle} · généré le {report.generatedAt}</div>
        </div>
        <button
          type="button"
          className="rp-toolbar-print"
          onClick={() => window.print()}
          aria-label={u.downloadPdf}
        >
          {u.downloadPdf}
        </button>
      </div>

      <div className="rp-sheet" ref={containerRef}>
        {/* MASTHEAD */}
        <div className="rp-masthead">
          <div className="rp-kicker">{u.kicker}</div>
          <h1>{report.title}</h1>
          <div className="rp-sub">{report.subtitle}</div>
          <div className="rp-meta-row">
            {report.meta.map((m, i) => (
              <div key={i}>
                <div className="rp-lab">{m.label}</div>
                <div className="rp-val">{m.value}</div>
              </div>
            ))}
          </div>
        </div>

        {/* 01 SYNTHÈSE */}
        <section className="rp-pad">
          <div className="rp-eyebrow">
            <span className="rp-num">01</span>
            <h2>{u.s01}</h2>
            <span className="rp-tag">{u.s01tag}</span>
          </div>
          <p className="rp-lead">{report.synthese}</p>

          <div className="rp-msgs">
            {report.execMessages.map((m, i) => (
              <div key={i} className={`rp-msg rp-msg-${m.tone}`}>
                <span className="rp-msg-h">{m.heading}</span>
                <span className="rp-msg-big" style={{ color: TONE_COLOR_BIG[m.tone] }}>{m.big}</span>
                <span className="rp-msg-b">{m.body}</span>
              </div>
            ))}
          </div>

          {/* FUNNEL */}
          <div className="rp-funnel">
            <div className="rp-funnel-track">
              {report.funnel.map((f, i) => (
                <div
                  key={i}
                  className="rp-fstage"
                  style={{ background: FUNNEL_BG[i % FUNNEL_BG.length], flexGrow: funnelFlex[i] }}
                >
                  <span className="rp-fn">{f.count.toLocaleString("fr-FR")}</span>
                  <span className="rp-fl">{f.label}</span>
                  {f.pct && <span className="rp-fpct">{f.pct}</span>}
                </div>
              ))}
            </div>
          </div>
        </section>

        {/* 02 KPIs */}
        <section className="rp-pad">
          <div className="rp-eyebrow">
            <span className="rp-num">02</span>
            <h2>{u.s02}</h2>
            <span className="rp-tag">{u.s02tag}</span>
          </div>
          <div className="rp-kpis">
            {report.kpis.map((k, i) => (
              <div key={i} className={`rp-kpi rp-kpi-${k.tone ?? "neutral"}`}>
                <div className="rp-kpi-v">{k.value}</div>
                <div className="rp-kpi-k">{k.label}</div>
                {k.hint && <div className="rp-kpi-note">{k.hint}</div>}
              </div>
            ))}
          </div>
        </section>

        {/* 03 PLAN D'ACTION */}
        {report.actionTiers.length > 0 && (
          <section className="rp-pad rp-page-break">
            <div className="rp-eyebrow">
              <span className="rp-num">03</span>
              <h2>{u.s03}</h2>
              <span className="rp-tag">{u.s03tag}</span>
            </div>
            {report.actionTiers.map((tier, i) => (
              <div key={i} className="rp-prio">
                <div
                  className="rp-prio-head"
                  style={{ background: PRIO_HEAD_BG[tier.priority] ?? "#5A6B82" }}
                >
                  <span className="rp-pn">{tier.priority}</span>
                  <span className="rp-pt">{tier.title}</span>
                  <span className="rp-pc">{tier.rows.length} {tier.rows.length > 1 ? u.dossiers : u.dossier}</span>
                </div>
                <div className="rp-prio-body">
                  <table>
                    <thead>
                      <tr>
                        <th>{u.colPatient}</th>
                        <th>{u.colPhone}</th>
                        <th>{u.colReason}</th>
                        <th>{u.colWhen}</th>
                        <th>{u.colUrgency}</th>
                      </tr>
                    </thead>
                    <tbody>
                      {tier.rows.map((r, j) => (
                        <tr key={j}>
                          <td className="rp-name">{r.name}</td>
                          <td className="rp-muted" style={{ fontFamily: "ui-monospace, Menlo, monospace", fontSize: 12 }}>{r.phone ?? "—"}</td>
                          <td>{r.reason}</td>
                          <td className="rp-when">{r.when ?? "—"}</td>
                          <td>
                            {r.urgency && (
                              <span className={`rp-pill rp-pill-${URGENCY_TONE[r.urgency]}`}>
                                {r.urgency === "haute" ? u.urgHaute : r.urgency === "moy" ? u.urgMoy : r.urgency === "surv" ? u.urgSurv : u.urgOk}
                              </span>
                            )}
                          </td>
                        </tr>
                      ))}
                    </tbody>
                  </table>
                </div>
              </div>
            ))}
          </section>
        )}

        {/* 04 VIGILANCE */}
        {report.vigilance.length > 0 && (
          <section className="rp-pad rp-page-break">
            <div className="rp-eyebrow">
              <span className="rp-num">04</span>
              <h2>{u.s04}</h2>
              <span className="rp-tag">{u.s04tag}</span>
            </div>
            <div className="rp-flags">
              {report.vigilance.map((v, i) => (
                <div key={i} className={`rp-flag rp-flag-${v.tone}`}>
                  <h4>{v.heading}</h4>
                  <p>{v.body}</p>
                  {v.fix && (
                    <div className="rp-fix">
                      <b>{u.levier}</b> {v.fix}
                    </div>
                  )}
                </div>
              ))}
            </div>
          </section>
        )}

        {/* 05 ANNEXES */}
        {report.annexes.length > 0 && (
          <section className="rp-pad rp-page-break">
            <div className="rp-eyebrow">
              <span className="rp-num">05</span>
              <h2>{u.s05}</h2>
              <span className="rp-tag">{u.s05tag}</span>
            </div>
            {report.annexes.map((annex, i) => (
              <div key={i} style={{ marginBottom: 24 }}>
                <div className="rp-annex-h">
                  <span
                    className="rp-annex-chip"
                    style={{ background: ANNEX_LETTER_BG[annex.tone] }}
                  >
                    {annex.letter}
                  </span>
                  {annex.heading}
                </div>
                {annex.subheading && <div className="rp-annex-sub">{annex.subheading}</div>}
                <table>
                  <thead>
                    <tr>
                      {annex.columns.map((c) => (
                        <th key={c.key}>{c.label}</th>
                      ))}
                    </tr>
                  </thead>
                  <tbody>
                    {annex.rows.map((r, j) => (
                      <tr key={j}>
                        {annex.columns.map((c) => (
                          <td key={c.key}>{r[c.key] ?? "—"}</td>
                        ))}
                      </tr>
                    ))}
                  </tbody>
                </table>
              </div>
            ))}
          </section>
        )}

        {/* FOOTER */}
        <div className="rp-foot">
          <b>{u.footerNote}</b> {report.methodNote} &nbsp;·&nbsp;
          {u.footerSuffix}
        </div>
      </div>
    </div>
  );
}
